version: '3'

services:
  web:
    build: .
    container_name: blabla_user
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - ./blabla_user:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  db:
    image: postgres:15.3-alpine3.18
    container_name: blabla_user_db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - blabla_user_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
    blabla_user_db:
      driver: local
